# Generated by Django 4.1.5 on 2023-08-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referralsystemapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(max_length=6),
        ),
    ]
